export default {
  readOnly: state => state.readOnly,
  readOnlyTrue: state => state.readOnlyTrue,
  ztreeSelect: state => state.ztreeSelect,
  isRefreshTree: state => state.isRefreshTree,
  isAddEditShow: state => state.isAddEditShow,
  isLoading: state => state.isLoading,
  isListShow: state => state.isListShow,
  indexTreeOperateBtns: state => state.indexTreeOperateBtns,
  formData: state => state.formData,
  systemId: state => state.systemId,
  navigateMenus: state => state.navigateMenus,
  operateBtns: state => state.operateBtns,
  tableList: state => state.tableList,
  gridEntityInfo: state => state.gridEntityInfo,
  menuPages: state => state.menuPages,
  listGridColumnInfo: state => state.listGridColumnInfo,
  tableBtns: state => state.tableBtns,
  listTunnelOftenRecord: state => state.listTunnelOftenRecord,
  deptIds: state => state.deptIds,
  extraCondition: state => state.extraCondition
};
