export default {
  readOnly: state => state.readOnly,
  treeList: state => state.treeList,
  btnShow: state => state.btnShow,
  delBtnShow: state => state.delBtnShow,
  gridEntityInfo: state => state.gridEntityInfo,
  listGridColumnInfo: state => state.listGridColumnInfo,
  tableList: state => state.tableList,
  deptIds: state => state.deptIds,
  extraCondition: state => state.extraCondition,
  formData: state => state.formData,
  listCulvertRegularRecord: state => state.listCulvertRegularRecord,
  isAddEditShow: state => state.isAddEditShow,
  isListShow: state => state.isListShow,
  isLoading: state => state.isLoading,
  tableBtns: state => state.tableBtns,
  ztreeSelect: state => state.ztreeSelect,
  navigateMenus: state => state.navigateMenus,
  operateBtns: state => state.operateBtns,
  isIndex: state => state.isIndex
};
