export default {
  readOnly: state => state.readOnly,
  treeList: state => state.treeList,
  gridEntityInfo: state => state.gridEntityInfo,
  listGridColumnInfo: state => state.listGridColumnInfo,
  tableList: state => state.tableList,
  deptId: state => state.deptId,
  formData: state => state.formData,
  isAddEditShow: state => state.isAddEditShow,
  isListShow: state => state.isListShow,
  isLoading: state => state.isLoading,
  tableBtns: state => state.tableBtns,
  ztreeSelect: state => state.ztreeSelect,
  listBridgeTech: state => state.listBridgeTech,
  listBridgeRecord: state => state.listBridgeRecord,
  listBridgeSubStructure: state => state.listBridgeSubStructure,
  listBridgeSupStructure: state => state.listBridgeSupStructure,
  navigateMenus: state => state.navigateMenus,
  operateBtns: state => state.operateBtns,
  qrCodeData: state => state.qrCodeData
};
